baseURL = "https://art-licence.com"
disableLanguages = []
disqusShortname = ""
paginate = "4"
summaryLength = "30"
theme = "airspace-hugo"
title = "Art-Licence | Licensing Agency"
[Languages.en]
contentDir = "content/english"
copyright = "&copy; 2020 Design [Themefisher](https://themefisher.com) All Rights Reserved."
languageCode = "en-us"
languageName = "En"
weight = 1
[[Languages.en.menu.footer]]
URL = "contact"
name = "Contact"
weight = 3
[[Languages.en.menu.footer]]
URL = "our-license"
name = "Our license"
weight = 2
[[Languages.en.menu.footer]]
URL = "about"
name = "About"
weight = 1
[[Languages.en.menu.main]]
URL = "contact"
name = "Contact"
weight = 4
[[Languages.en.menu.main]]
URL = "our-license"
name = "Our license"
weight = 3
[[Languages.en.menu.main]]
URL = "about"
name = "About"
weight = 2
[[Languages.en.menu.main]]
URL = ""
name = "Home"
weight = 1
[Languages.tr]
contentDir = "content/turkish"
copyright = "&copy; 2020 Tasarım [Themefisher](https://themefisher.com) Tüm hakları saklıdır."
languageCode = "tr-tr"
languageName = "Tr"
weight = 2
[[Languages.tr.menu.footer]]
URL = "tr/contact"
name = "İletişim"
weight = 3
[[Languages.tr.menu.footer]]
URL = "tr/our-license"
name = "Lisanslarımız"
weight = 2
[[Languages.tr.menu.footer]]
URL = "tr/about"
name = "Hakkımızda"
weight = 1
[[Languages.tr.menu.main]]
URL = "contact"
name = "İletişim"
weight = 4
[[Languages.tr.menu.main]]
URL = "our-license"
name = "Lisanslarımız"
weight = 3
[[Languages.tr.menu.main]]
URL = "about"
name = "Hakkımızda"
weight = 2
[[Languages.tr.menu.main]]
URL = "tr"
name = "Anasayfa"
weight = 1
[params]
author = "Themefisher"
contact_form_action = "https://formspree.io/xvowbybb"
description = "Licencing Company"
email = "info@art-licence.com"
google_analitycs_id = ""
location = "Istanbul,Turkey"
logo = "images/logo.png"
mobile = ""
multi_author = false
[params.gmap]
enable = false
gmap_api = "https://maps.googleapis.com/maps/api/js?key=AIzaSyCcABaamniA6OL5YvYSpB3pFMNrXwXnLwU&libraries=places"
map_latitude = "51.5223477"
map_longitude = "-0.1622023"
map_marker = "images/marker.png"
[params.nav_button]
enable = true
label = "Get A Quote"
link = "contact"
[[params.plugins.css]]
link = "plugins/bootstrap/bootstrap.min.css"
[[params.plugins.css]]
link = "plugins/Ionicons/css/ionicons.min.css"
[[params.plugins.css]]
link = "plugins/magnific-popup/magnific-popup.css"
[[params.plugins.css]]
link = "plugins/slick/slick.css"
[[params.plugins.js]]
link = "plugins/jQuery/jquery.min.js"
[[params.plugins.js]]
link = "plugins/bootstrap/bootstrap.min.js"
[[params.plugins.js]]
link = "plugins/slick/slick.min.js"
[[params.plugins.js]]
link = "plugins/magnific-popup/jquery.magnific-popup.min.js"
[[params.plugins.js]]
link = "plugins/shuffle/shuffle.min.js"
[[params.plugins.js]]
link = "plugins/google-map/gmap.js"
[params.preloader]
enable = true
preloader = "images/loader.gif"
[params.widgets]
sidebar = ["recent_posts", "taxonomy_category", "taxonomy_tags"]
[[params.social]]
icon = "ion-social-linkedin-outline"
link = "#"
[[params.social]]
icon = "ion-social-pinterest-outline"
link = "#"
[[params.social]]
icon = "ion-social-dribbble-outline"
link = "#"
[[params.social]]
icon = "ion-social-twitter-outline"
link = "#"
[[params.social]]
icon = "ion-social-facebook-outline"
link = "#"
